name: $(SourceBranch)$(Rev:.r)
jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: GoTool@0
        displayName: 'Use Go 1.11'
        inputs:
          version: 1.11

      - script: go build
        displayName: Build

      - script: go test ./...
        displayName: Test

      - powershell: |
          $branch = $env:BUILD_SOURCEBRANCH
          $buildType = "-test"
          
          If ($branch -like "refs/heads/master") {
              $buildType="-master"
          }

          $pkgVersion = ./batch-insights --version
          $version = "$pkgVersion$buildType.$env:BUILD_NUMBER"
          Write-Host "Version is $version"
          Write-Host "##vso[build.updatebuildnumber]$version"
        displayName: Update build name

      - task: CopyFiles@2
        inputs:
          contents: batch-insights
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'linux' 


  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: GoTool@0
        displayName: 'Use Go 1.11'
        inputs:
          version: 1.11

      - script: |
          set GOARCH=amd64
          echo "GO arch %GOARCH%"
          go build
        displayName: Build

      - script: go test ./...
        displayName: Test
        
      - task: CopyFiles@2
        inputs:
          contents: batch-insights.exe
          targetFolder: $(Build.ArtifactStagingDirectory)
          
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: 'windows' 
